/**
 * Codes de permission alignés backend (JWT / claims).
 * Les rôles ne font qu’agréger des permissions — l’UI et les guards s’appuient sur ces codes.
 */
export const P = {
  VIEW_GLOBAL_DASHBOARD: 'VIEW_GLOBAL_DASHBOARD',
  VIEW_STORE_DASHBOARD: 'VIEW_STORE_DASHBOARD',

  VIEW_PRODUCTS: 'VIEW_PRODUCTS',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  EDIT_PRODUCT: 'EDIT_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',

  VIEW_STOCK: 'VIEW_STOCK',
  ADJUST_STOCK: 'ADJUST_STOCK',

  VIEW_MOVEMENTS: 'VIEW_MOVEMENTS',
  CREATE_MOVEMENT: 'CREATE_MOVEMENT',
  VALIDATE_MOVEMENT: 'VALIDATE_MOVEMENT',
  TRANSFER_STOCK: 'TRANSFER_STOCK',

  VIEW_ALERTS: 'VIEW_ALERTS',
  MANAGE_ALERTS: 'MANAGE_ALERTS',

  VIEW_STORES: 'VIEW_STORES',
  MANAGE_STORES: 'MANAGE_STORES',

  VIEW_REPORTS: 'VIEW_REPORTS',
  EXPORT_REPORTS: 'EXPORT_REPORTS',

  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  MANAGE_CATEGORIES: 'MANAGE_CATEGORIES',
} as const;

export type AppPermission = (typeof P)[keyof typeof P];

export const ALL_APP_PERMISSIONS: AppPermission[] = Object.values(P);
